name: Create Release

on:
  push:
    tags:
      - 'v*' # Dispara o workflow quando uma tag no formato "vX.X.X" é criada

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token automático fornecido pelo GitHub
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true # Gera notas de release automaticamente

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/your-artifact.jar # Caminho para o arquivo que deseja anexar
          asset_name: your-artifact.jar
          asset_content_type: application/java-archive
